targets:
  $default:
    sources:
      - lib/**
      - graphql/**
    builders:
      artemis:
        options:
          schema_mapping:
            - schema: graphql/github/schema.graphql
              queries_glob: graphql/github/{queries,mutations}/*.graphql
              output: lib/graphql/github/api.dart
          custom_parser_import: 'package:github_contribution_graph_summary/coercers.dart'
          scalar_mapping:
            - graphql_type: GitObjectID
              dart_type: String
            - graphql_type: URI
              dart_type: String
            - graphql_type: Date
              dart_type: DateTime
            - graphql_type: DateTime
              dart_type: DateTime
